services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: ./app
    ports: 
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

volumes:
  mysql-data:
  jenkins-data:
